[한성봉] ADD: 카카오/구글 로그인 기능 구현
wecode-bootcamp-korea/21-2nd-GroundBnB-backend pull request #7
Opened 2021-06-28 04:30 UTC by SSABOODA

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 로그인 기능 구현
- 구글 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카카오 로그인 시 기존 유저 유무에 따라 토큰 발급
- 구글 로그인 시 기존 유저 유무에 따라 토큰 발급

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-29 02:25 UTC, lordmyshepherd requested changes

2021-06-29 02:25 UTC, lordmyshepherd commented on users/views.py
> +
피드백 다음과 같이 드릴 수 있을 것 같아요!
KakaoAPI를 class로 만들어서 관리할 수 있을 것 같습니다. 
class로 관리하게 되면, 구현체(실제 실행되는 로직)은 몰라도 Interface만 가져다가 사용하면 되므로, View가 짧아지고 가독성이 높아집니다.
두번째는 kakao map을 사용하는 경우에도 해당 로직을 `KakaoAPI` 클래스에 넣어서 관리할 수 있는 장점이 있습니다.

(추가 피드백)
1. requests 라이브러리 사용시 반드시 timeout을 걸어줘야 합니다. 그렇지 않으면 우리 서버가 요청에 대한 응답을 계속 기다리게 됩니다.
2. error 발생 상황 고려하신 것 정말 good입니다!! 다만 status code로 비교해주세요~

```python
class KakaoAPI:
    KAKAO_API_URL = "https://kapi.kakao.com/v2/user/me"

    def __init__(self, token):
        self.token = token
    
    def get_kakao_user(self):
        headers  = {"Authorization" : f"Bearer {self.token}"}
        response = request.get(API_URL, headers = headers, timeout=..)
        
        if response.status != 200:
            return JsonResponse({'MESSAGE' : error_massage}, status=400)
        
        return response.json()["kakao_account"]


class GoogleAPI:
    def get_google_user(self, token):
        ...
        

```

2021-06-29 02:25 UTC, lordmyshepherd commented on users/views.py
> +            profile = kakao_account.get("profile", None)
```suggestion

        kakao_user = KakaoAPI(kakao_token)
```

2021-06-29 02:52 UTC, lordmyshepherd requested changes

2021-06-29 02:52 UTC, lordmyshepherd commented on users/views.py
> +            profile = kakao_account.get("profile", None)
line 14~27은 전부 지워도 되겠네요~

2021-06-29 02:52 UTC, lordmyshepherd commented on users/views.py
> +                social_user_provider_id.append(i.provider_id)
이부분이 왜 필요한가요?

2021-06-29 02:52 UTC, lordmyshepherd commented on users/views.py
> +                )
```suggestion 
        user, created = User.objects.get_or_create(
            social_provider__id            = kakao_user["id"], 
            social_provider__provider_name = 'kakao'
        )
        
        if created:
            SocialFlatform.objects.create(
                provider_name = 'kakao',
                provider_id   = kakao_user_info.get('id'), 
                profile_image = profile.get('profile_image_url'),
                nick_name     = profile.get('nickname'),
                user          = user
            )

            user.name = profile.get('nickname')
            ..
            user.save()
            
        return JsonResponse({'access_token': access_token}, status=200)
```

2021-06-29 02:52 UTC, lordmyshepherd commented on users/views.py
> +                )
`get_or_create()` method를 사용하면 위와 같이 중복되는 코드 없이 줄일 수 있을 것 같네요~

2021-06-29 10:58 UTC, SSABOODA commented on users/views.py
> +
네 리뷰 반영하여 api로직을 클래스로 따로 빼서 구현하였습니다. 근데 api클래스를 같은 뷰에 나둬서 사용하면 되는 건가요?

2021-06-29 10:59 UTC, SSABOODA commented on users/views.py
> +            profile = kakao_account.get("profile", None)
네 수정하였습니다.

2021-06-29 10:59 UTC, SSABOODA commented on users/views.py
> +                social_user_provider_id.append(i.provider_id)
그 기존 유저인가 비교하는 로직을 짜려고 했는데 get_or_create 메서드를 사용하니 불필요한 로직이었습니다. 수정하였습니다.

2021-06-29 11:00 UTC, SSABOODA commented on users/views.py
> +                )
네 말씀해주신 메서드를 활용하여 로직 수정하였습니다.

2021-06-30 02:29 UTC, lordmyshepherd commented on users/views.py
> +
👍  지금은 view에 코드가 많지 않으니 상관없는데, 코드가 많아지면 KakaoAPI, GoogleAPI 같은 class는 다른 모듈(예를 들어서 `common`)로 빼는게 좋습니다.

2021-06-30 06:37 UTC, lordmyshepherd commented
오프라인에서 피드백드린 내용으로 수정해주세요~~~
그리고 추가로 컨플릭트도 해결해주세요 성봉님~~ 👍

2021-07-01 01:21 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-01 01:21 UTC, lordmyshepherd commented on users/tests.py
> +# from groundbnb.settings.local import LOCAL_SECRET_KEY, ALGORITHM
사용하지 않는 주석은 지워주세요~

2021-07-01 01:21 UTC, lordmyshepherd commented on users/tests.py
> +        responce.json()['access_token'] = 'access_token'
오타가 있네요! 그런데 여기서 어떻게 스트링인 'access_token'이 반환되는거죠? 암호화된 토큰이 발급되야 하는거 아닌가요??

```suggestion
        response = client.get("/users/login/kakao", **headers)

        response.json()['access_token'] = 'access_token'
```

2021-07-01 01:21 UTC, lordmyshepherd commented on users/utils.py
> +
빈 줄은 지워주세요!
파이썬에서 빈 줄까지 다 읽어버립니다!

2021-07-01 01:21 UTC, lordmyshepherd commented on users/utils.py
> +def UserTokenDeco(func):
`decorator`도 `nested function`이기 때문에 함수명을 아래와 같은 형태로 만들어주는게 좋습니다!
대문사는 class나 일반 상수에서만 사용합니다!

```suggestion
def login_required(func):
```

2021-07-01 01:21 UTC, lordmyshepherd commented on users/views.py
> +
```suggestion
            kakao_api   = KakaoAPI(access_token)            
            kakao_user = kakao_api.get_kakao_user()            
```

2021-07-01 01:21 UTC, lordmyshepherd commented on users/views.py
> +                email = kakao_account.get('email')
```suggestion
                email = kakao_user["account"]["email"]
```

2021-07-01 01:21 UTC, lordmyshepherd commented on users/views.py
> +            google_provider_id     = google_user_info.get('id')
```suggestion
            google_api       = GoogleAPI(access_token)
            google_user       = google_login_api.get_google_user()
```

2021-07-01 01:21 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-07-01 01:38 UTC, SSABOODA commented on users/tests.py
> +# from groundbnb.settings.local import LOCAL_SECRET_KEY, ALGORITHM
네 수정 하였습니다.~~~

2021-07-01 01:38 UTC, SSABOODA commented on users/tests.py
> +        responce.json()['access_token'] = 'access_token'
넵 수정하였습니다.

2021-07-01 01:39 UTC, SSABOODA commented on users/views.py
> +
넵 수정하였습니다.~

2021-07-01 01:40 UTC, SSABOODA commented on users/views.py
> +                email = kakao_account.get('email')
수정하였습니다.~~

2021-07-01 01:40 UTC, SSABOODA commented on users/views.py
> +            google_provider_id     = google_user_info.get('id')
수정하였습니다.~~

2021-07-01 06:45 UTC, SSABOODA commented on users/utils.py
> +def UserTokenDeco(func):
넵 데코레이터 브랜치에서 수정하였습니다

2021-07-01 06:45 UTC, SSABOODA commented on users/utils.py
> +
넵 수정하였습니다.

2021-07-01 08:10 UTC, lordmyshepherd commented
LGTM 👍

2021-07-01 08:11 UTC, lordmyshepherd commented
고생 많으셨습니다 성봉님!!!

2021-07-01 08:11 UTC, merged