[한성봉] Feature/socaillogout
wecode-bootcamp-korea/21-2nd-GroundBnB-backend pull request #8
Opened 2021-06-28 08:03 UTC by SSABOODA

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 로그아웃 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카카오 로그아웃 기능 구현 / 토큰 만료 시킴

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-30 06:39 UTC, lordmyshepherd requested changes
해당 PR에는 로그아웃 코드만 남겨주세요!

2021-06-30 06:39 UTC, lordmyshepherd commented on users/utils.py
> +def UserTokenDeco(func):
이미 이전 PR에 있는 코드네요 삭제해주세요!

2021-07-01 01:43 UTC, lordmyshepherd requested changes

2021-07-01 01:43 UTC, lordmyshepherd commented on users/views.py
> +class KakaoAPI:
잘 작성해주셨네요! 👍

2021-07-01 01:43 UTC, lordmyshepherd commented on users/tests.py
> +    def test_kakao_signin_new_user_success(self, mocked_requests):
signin 유닛테스트 아닌가요?
이번 pr에는 logout기능인데 테스트코드는 다른게 올라온 것 같아요! 확인 부탁드려요~

2021-07-01 02:08 UTC, SSABOODA commented on users/utils.py
> +def UserTokenDeco(func):
네 수정했습니다~

2021-07-01 02:08 UTC, SSABOODA commented on users/views.py
> +class KakaoAPI:
감사합니다^^

2021-07-01 02:08 UTC, SSABOODA commented on users/tests.py
> +    def test_kakao_signin_new_user_success(self, mocked_requests):
넵 수정했습니다.~

2021-07-01 08:11 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-07-01 08:35 UTC, lordmyshepherd commented
LGTM 👍

2021-07-01 08:35 UTC, merged