[한성봉] 로그인 데코레이터 구현
wecode-bootcamp-korea/21-2nd-GroundBnB-backend pull request #9
Opened 2021-06-29 11:48 UTC by SSABOODA

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 데코레이터 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 데코레이터 구현
- 현재 로직 상 필요한 퍼블릭, 프라이빗 데코레이터 추가 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-30 06:40 UTC, lordmyshepherd commented
로그인 데코레이터도 이미 첫번째 PR에 포함되어 있는 것 같습니다!

2021-07-01 01:40 UTC, lordmyshepherd requested changes

2021-07-01 01:40 UTC, lordmyshepherd commented on users/utils.py
> +def UserTokenDeco(func):
지난번에 피드백 드린 내용이 반영이 안되어 있는 것 같아요!
decorator 함수명은 `login_required` 등으로 수정해주세요!

`UserTokenDeco`는 class를 만들때 사용하는 컨벤션입니다!

2021-07-01 01:40 UTC, lordmyshepherd commented on users/utils.py
> +def PublicUserDeco(func):
여기도 마찬가지입니다.

해당 데코레이터는 어디 엔드포인트에 붙이는 건가요?

2021-07-01 02:10 UTC, SSABOODA commented on users/utils.py
> +def UserTokenDeco(func):
넵 수정하였습니다.

2021-07-01 05:58 UTC, closed without merging